language: python
python:
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python -m pytest --cov .
after_success:
  - coveralls
  - tar -zcvf raspberry_files.tgz cmd_config.py config.py find_probes.py install.sh record_data.py
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: raspberry_files.tgz
  skip_cleanup: true
  on:
    tags: true