language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
script:
  - python -m pytest --cov .
after_success:
  - coveralls
  - codecov
  - tar -zcvf files.tgz -T tar_files.txtpip inst
deploy:
  provider: releases
  api_key:
    secure: OjhsyL9ayg22GcHS6CxrLviQ6bkNoGHZ4srSNfPOFlGUANLQpGLuoZP1Jh0pkupHkWvDT50uGf9ihbW4VtvZBlF4H1dS5A3gNgbKWytiPmLnYx4wWs932buwdLSL8N64nKnDMySJCYfwg9D5nU26yQ7bCvm2tAlME0yip582z0rd8Ww6RYb0oUkW5rTmCsAQyUuwcu5DREjC07L3F6XumPMWC2ay4BV9NnR1Z77RiENcqfB5ZwfMZWmJVcefwKhqfMeljUXoaxAo69/SXiZ+ehRSwlMl2ieRBmXC+9tj4cflbdRrHrhboVPomLYn3YqvlMTeu9DF0V1eI1A3N+TVqfepWmvI02XJwi19f8efqv/nN+CSMHjt7pf2QE4dsHY2b1AEd8nCM6SpOEf6txR6ws9FS7BcyzN9MnNQUXI9DH8eC+w1vHJzLY6L49DPwmXciIBZxfnI79r7cqK+My9EqYjMo2GhvvNhOWNnm6GnclL3jRIcJBskmCCH+Q8KcS9FGWgWekAaZLfK+aRY7Xgmr5RRfvv4v1iNTWIwLk6drT4q2Fmvn14glL5eiVJp1RNqI5Jj61Xv1K1Jd1exZE4ySXA8sHSYInXfb6roShvNTAVtusup9UqfMV81MOTOljyLEsahGA5V9B8czNTzCXOtqL7oVtvfWn6bn3+++Dc86DE=
  file: files.tgz
  skip_cleanup: true
  on:
    tag: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^release-*
    name: $TRAVIS_TAG