language: python
python:
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov coveralls
script:
  - coverage run -m pytest --cov=bee_pi
after_success:
  - coveralls