version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    #      - image: resin/raspberrypi3-python
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Virtual Environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install coverage
            which coverage
      - run:
          name: Run Coverage Report
          command: |
            coverage report && coverage xml -o test-reports/coverage/coverage.xml
      - run:
          name: Run Tox Report
          command: |
            tox

      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: test-reports/