version: 2.0
jobs:
 build:
   docker:
     - image: resin/raspberrypi3-python
   steps:
     - run:
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements.txt
     - run: mkdir test-reports
     - run: coverage report && coverage xml -o test-reports/coverage/coverage.xml
     - run:
         command: |
           tox
     - store_test_results:
         path: test-reports
     - store_artifacts:
         path: test-reports/tox
     - store_artifacts:
         path: test-reports/coverage

workflows:
  version: 2

  testproject:
    jobs:
      - build