version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    #      - image: resin/raspberrypi3-python
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Virtual Environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt
            sudo pip install pytest pytest_cov
      - run:
          name: Run Test with Coverage Report
          command: |
            coverage run -m pytest --cov . --cov-report=xml:.coverage
            coverage run -m pytest --cov . --cov-report=xml:test-reports/coverage.xml
            coverage report
            coveralls
      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: test-reports/
