version: 2.0
jobs:
 build:
   docker:
     - image: resin/raspberrypi3-python
   steps:
     - run:
         name: The First Step
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
     - run:
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements.txt
     - run: mkdir test-reports
     - run: coverage report && coverage xml -o test-reports/coverage.xml
     - store_test_results:
         path: test-reports
     - store_artifacts:
         path: test-reports
         destination: tr1
     - run:
         command: |
           tox
     - run:
         command: |
           cat test-reports/tox.xml
workflows:
  version: 2

  testproject:
    jobs:
      - build