version: 2.0
jobs:
 build:
   docker:
     - image: resin/raspberrypi3-python
   steps:
     - run:
         name: The First Step
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
     - run:
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements.txt
     - run:
         command: |
           tox
#language: python
#python:
#  - "3.7"
#install:
#  - pip install -r requirements.txt

#script: pytest