version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    #      - image: resin/raspberrypi3-python
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Virtual Environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo pip install pytest coverage python-coveralls
#      - run:
#          name: Run Coverage Report
#          command: |
#            coverage report && coverage xml -o test-reports/coverage/coverage.xml
#            coveralls
      - run:
          name: Run Tests
          command: |
            export PYTHONPATH=`pwd`:$PYTHONPATH
            pytest tests/test_config.py --junitxml=test-reports/tox/tox.xml
            coveralls
#            tox

      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: test-reports/