version: 2.0
jobs:
  build:
    docker:
      - image: resin/raspberrypi3-python
    steps:
      - checkout
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir tmp
            echo "my artifact file" > tmp/artifact-1;
            mkdir tmp/artifacts;
            echo "my artifact files in a dir" > tmp/artifacts/artifact-2;
      - run:
          name: Install Virtual Environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
#     - run:
#         name: Create Test Reports Directory
#         command: |
#           mkdir tests
#     - run:
#         name: Run Coverage Report
#         command: |
#           coverage report && coverage xml -o tests/coverage/coverage.xml
#     - run:
#         name: Run Tox Report
#         command: |
#           tox

      - store_test_results:
          path: tmp

      - store_artifacts:
          path: ./tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: ./tmp/artifacts

#     - store_artifacts:
#         path: ./tests