version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    #      - image: resin/raspberrypi3-python
    steps:
      - checkout
      - run:
          name: Install Virtual Environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Coverage Report
          command: |
            coverage report && coverage xml -o tests/coverage/coverage.xml
      - run:
          name: Run Tox Report
          command: |
            tox
            
      - store_test_results:
          path: tests
      - store_artifacts:
          path: ./tests