version: 2.0
jobs:
 build:
   docker:
     - image: resin/raspberrypi3-python
   steps:
     - run:
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements.txt
     - run: mkdir test-reports
     - run: coverage report && coverage xml -o tests/coverage/coverage.xml
     - run:
         command: |
           tox
     - run:
         command: |
           cat tests/tox.xml
     - store_test_results:
         path: tests
     - store_artifacts:
         path: tests
         destination: tox
         
workflows:
  version: 2

  testproject:
    jobs:
      - build