version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    #      - image: resin/raspberrypi3-python
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Virtual Environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo pip install pytest pytest-cov python-coveralls
      - run:
          name: Run Test with Coverage Report
          command: |
            coverage run -m pytest --cov=bee_pi --cov-report=xml:.coverage
            cp .coverage test-reports/coverage.xml
            coveralls
#            coverage run -m pytest --cov=bee_pi --cov-report=xml:test-reports/coverage.xml
#            pytest tests/test_config.py --junitxml=test-reports/tox/tox.xml --cov=bee_pi format=coverage --cover-xml
#      - run:
#          name: Run Tests
#          command: |
#            export PYTHONPATH=`pwd`:$PYTHONPATH
#            pytest tests/test_config.py --junitxml=test-reports/tox/tox.xml --cov=bee_pi format=coverage --cover-xml
#            coveralls
#            tox

      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: test-reports/