version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    #      - image: resin/raspberrypi3-python
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Virtual Environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
<<<<<<< HEAD
            sudo pip install pytest coverage
      - run:
          name: Run Coverage Report
          command: |
#            coverage report && coverage xml -o test-reports/coverage/coverage.xml
            coverage run *.py && coverage report && coveralls
      - run:
          name: Run Tests
          command: |
            pytest test_config.py --junitxml=test-reports/tox/tox.xml
#            tox
=======
            sudo pip install pytest pytest-cov python-coveralls
      - run:
          name: Run Test with Coverage Report
          command: |
            coverage run -m pytest --cov=bee_pi --cov-report=xml:.coverage
            coverage run -m pytest --cov=bee_pi --cov-report=xml:test-reports/coverage.xml
            coveralls
###
#            coverage run -m pytest --cov=bee_pi --cov-report=xml:test-reports/coverage.xml
#            pytest tests/test_config.py --junitxml=test-reports/tox/tox.xml --cov=bee_pi format=coverage --cover-xml
#      - run:
#          name: Run Tests
#          command: |
#            tox
#            coveralls
#            pytest tests/test_config.py --junitxml=test-reports/tox/tox.xml --cov=bee_pi format=coverage --cover-xml
>>>>>>> origin/master

      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: test-reports/