"""empty message

Revision ID: dbcf1e1b5d75
Revises: 
Create Date: 2017-10-04 21:12:55.599564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcf1e1b5d75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stateProvince',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('countryId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['countryId'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetAddress', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('stateProvinceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stateProvinceId'], ['stateProvince.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('passwd', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=400), nullable=True),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locationId'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['locationId'], ['location.id'], ),
    sa.ForeignKeyConstraint(['ownerId'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiveData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hiveId', sa.Integer(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('humidity', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['hiveId'], ['hive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hiveData')
    op.drop_table('hive')
    op.drop_table('owner')
    op.drop_table('location')
    op.drop_table('stateProvince')
    op.drop_table('country')
    # ### end Alembic commands ###
